#!/usr/bin/env python3
""" Skeleton Implementation of Project 2 for NEU CS3700 """

import argparse
import json
import select
import socket

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################

class Router:
  """ Your Router """
  def __init__(self, networks):
    self.asn = networks.pop(0)
    self.routes = {} #forwarding table
    self.updates = {} #store announcements
    self.relations = {} #cust, peer, etc.
    self.sockets = {}
    for relationship in networks:
      network, relation = relationship.split("-")
      self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
      self.sockets[network].setblocking(0)
      self.sockets[network].connect(network)
      self.relations[network] = relation

  def lookup_routes(self, daddr):
    """ Lookup all valid routes for an address """
    # TODO
    outroutes = []

    net_pre = daddr[0 : daddr.index('.')] + '.0.0.0'

    #print(self.routes)

    for ip in self.routes.keys():
      network = self.routes[ip][NTWK]
      net_pre_2 = network[0:network.index('.')] + '.0.0.0'
      if net_pre_2 == net_pre:
        outroutes.append(ip)
    return outroutes

  def get_shortest_as_path(self, routes):
    """ select the route with the shortest AS Path """
    # Max size of route below
    size = 999;
    outroutes = {}

    for ip in routes.keys():
      if len(routes[ip][APTH]) < size:
        size = len(routes[ip][APTH])

    for ip in routes.keys():
      if len(routes[ip][APTH]) == size:
        outroutes[ip] = routes[ip]

    return outroutes

  def get_highest_preference(self, routes):
    """ select the route with highest preference """
    # routes is all possible routes to daddr
    outroutes = {}
    highest = 0

    for ip in routes.keys():
      if routes[ip][LPRF] > highest:
        highest = routes[ip][LPRF]

    for ip in routes.keys():
      if routes[ip][LPRF] == highest:
        outroutes[ip] = routes[ip]

    return outroutes

  def get_self_origin(self, routes):
    """ select self originating routes """
    # TODO
    outroutes = {}

    for ip in routes.keys():
      if routes[ip][SORG]:
        outroutes[ip] = routes[ip]

    return outroutes

  def get_origin_routes(self, routes):
    """ select origin routes:  IGP > EGP > UNK """
    # TODO
    outroutes = {}

    for ip in routes.keys():
      if routes[ip][ORIG] == "IGP":
        outroutes[ip] = routes[ip]

    if len(outroutes) == 0:
      for ip in routes.keys():
        if routes[ip][ORIG] == "EGP":
          outroutes[ip] = routes[ip]

    # If no IGP nor EGP were found return rest of routes bc UNK
    if len(outroutes) == 0:
      return routes

    return outroutes

  def filter_relationships(self, srcip, routes):
    """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
    outroutes = []
    return outroutes

  def prefix_stuff(self, daddr, routes):

    outroutes = []
    #find prefix in routes matching daddr
    #look in self.routes for netmask on possible routes
    #longer wins

    highestmsk = 0

    for ip in routes:
      netmask = self.routes[ip][NMSK] #get netmask of possible ip
      ii1 = netmask.index('.')
      ii2 = netmask.index('.', ii1 + 1)
      ii3 = netmask.index('.', ii2 + 1)
      n1 = netmask[0: ii1]
      n2 = netmask[ii1 + 1: ii2]
      n3 = netmask[ii2 + 1: ii3]
      n4 = netmask[ii3 + 1: len(netmask)]
      maskval = int(n1) + int(n2) + int(n3) + int(n4)
      if maskval > highestmsk:
        highestmsk = maskval

    for ip in routes: #loop through possible ips and find ones matching the ntmsk
      netmask = self.routes[ip][NMSK]  # get netmask of possible ip
      ii1 = netmask.index('.')
      ii2 = netmask.index('.', ii1 + 1)
      ii3 = netmask.index('.', ii2 + 1)
      n1 = netmask[0: ii1]
      n2 = netmask[ii1 + 1: ii2]
      n3 = netmask[ii2 + 1: ii3]
      n4 = netmask[ii3 + 1: len(netmask)]
      maskval = int(n1) + int(n2) + int(n3) + int(n4)
      if maskval == highestmsk:
        outroutes.append(ip)

    return outroutes

  def get_route(self, srcip, daddr): #destinations add of this packet
    """ Select the best route for a given address """
    # TODO fill in peer?
    peer = None

    pos_routes = self.lookup_routes(daddr)

    #prefix stuff

    pos_routes = self.prefix_stuff(daddr, pos_routes) #look through possible
                                                      #and find prefix matching destination ip

    # Rules go here
    #if pos_routes:
      # 1. Highest Preference
      #pos_routes = self.get_highest_preference(pos_routes)
      # 2. Self Origin
     # pos_routes = self.get_self_origin(pos_routes)
      # 3. Shortest ASPath
     # pos_routes = self.get_shortest_as_path(pos_routes)
      # 4. EGP > IGP > UNK
     # pos_routes = self.get_origin_routes(pos_routes)
      # 5. Lowest IP Address

      #daddrbit = self.ip_to_bits(daddr)

      # Final check: enforce peering relationships

      #route = self.filter_relationships(srcip, pos_routes)
      #lowestip = 0;


    peer = pos_routes[0]

    return self.sockets[peer] if peer else None

  def forward(self, srcip, packet): #gets entire packet and srcip of that packet
    """ Forward a data packet """
    # get route to send packet
    best_route = self.get_route(srcip, packet[DEST]) #is a socket

    sock = best_route


    jsonpack = json.dumps(packet)
    sock.sendall(jsonpack.encode())
    # TODO fix src and dest
    return True

  def coalesce(self):
    """ coalesce any routes that are right next to each other """
    # TODO (this is the most difficult task, save until last)   
    return False

  def update(self, srcip, packet):
    """ handle update packets """

    # TODO save copy of announcement

    #print("the src ip: " + str(srcip))
    self.updates[srcip] = packet #entire packet
    #print("the update packet originally")
    #print(json.dumps(self.updates[srcip], sort_keys=True, indent=4))
    # add entry to forwarding table
    path = packet[MESG][APTH]
    path.append(self.asn)
    packet[MESG][APTH] = path
    #print("the update message after apath")
    msg = packet[MESG]
    #print(json.dumps(msg, sort_keys=True, indent=4))
    self.routes[srcip] = msg

    # decide if send copies of announcement to neighboring routers

    for ip in self.sockets.keys():
      if not(ip == srcip):
        #get the .1 version of the ip i'm sending update to
        #ip i'm sending to is ip
        dest_ip_port = list(ip)
        dest_ip_port[len(ip) - 1] = '1'
        packet['src'] = ''.join(dest_ip_port)
        packet['dst'] = ip

        #print("the packet im sending")
        #print(json.dumps(packet, sort_keys=True, indent=4))

        #print("the socket ip i'm sending it to: " + ip)

        jsonpack = json.dumps(packet)

        self.sockets[ip].sendall(jsonpack.encode())

    # TODO
    return True

  def revoke(self, packet):
    """ handle revoke packets """
    # TODO
    return True

  def dump(self, packet):
    """ handles dump table requests """
    # TODO
    packet['type'] = "table"
    src = packet['src']
    packet['src'] = packet['dst']
    packet['dst'] = src

    table_list = []

    # TODO fill out table string with routing table
    table_string = ""
    # TODO asking for int indexes instead of string for route?
    for ip in self.updates.keys():
      # TODO have to fill ip address of peer

      entry = {'network' : self.updates[ip][MESG][NTWK], 'netmask' : self.updates[ip][MESG][NMSK], 'peer' : ip}
      table_list.append(entry)
    packet[MESG] = table_list
    msg = json.dumps(packet)
    #print(json.dumps(packet, sort_keys=True, indent=4))

    sock = self.sockets[src]
    sock.sendall(msg.encode())
    return True

  def handle_packet(self, srcip, packet):
    """ dispatches a packet """
    # TODO
    #print("REACHED HANDLE PACKET")
    type = packet['type']
    if type == 'update':
      self.update(srcip, packet)
      #print("sending to update")
    elif type == 'dump':
      self.dump(packet)
    elif type == 'data':
      # check if a route is in forwarding table
      # if so forward
      self.forward(srcip,packet)
      # TODO if no route found send to no route (Send error)


      #print("sending to forward")
    elif type == 'revoke':
      self.revoke(packet)
      #print("sending to revoke")

    return True

  def send_error(self, conn, msg):
    """ Send a no_route error message """
    # dst ip becomes src ip to return the message

    # src ip becomes this ip

    # type becomes "no route"

    # msg is empty

    # send from port incoming...current dst ip?

    # TODO

    return

  def run(self):
    """ main loop for the router """
    while True:
      socks = select.select(self.sockets.values(), [], [], 0.1)[0]
      for conn in socks:
        try:
          k = conn.recv(65535)
        except:
          # either died on a connection reset, or was SIGTERM's by parent
          return
        if k:
          for sock in self.sockets:
            if self.sockets[sock] == conn:
              srcip = sock
          msg = json.loads(k)
          # TODO commented out below code because handled by handle packet
          #self.update(srcip, msg)
          #print(msg[TYPE])
          #print(json.dumps(msg, sort_keys=True, indent=4))
          if not self.handle_packet(srcip, msg):
            self.send_error(conn, msg)
        else:
          return

if __name__ == "__main__":
  PARSER = argparse.ArgumentParser(description='route packets')
  PARSER.add_argument('networks', type=str, nargs='+', help="networks")
  args = PARSER.parse_args()
  networks = args.networks
  #print(networks)
  router = Router(args.networks).run()   #custruct router object and call run method
